$ANSIBLE_VAULT;1.1;AES256
30383339326336643961313163613661313732623034656235383163623637353830643937346635
3938346635663864616463613939373264643732643262300a383331363566346631666534383136
62653732643437656264646663303063353162633666626335343634323235666239353665346430
3964613761326265640a626337363265656333376563366566366361646630393334323933346230
36333636373637323839346566363262313036376639393932386439626435383064
