---
  - name : start  the play from a sepcific task
    hosts : localhost
    tasks: 
      - name : task1
        debug : 
          msg : hey i am task1
      
      - name : task2
        debug :
          msg : hey i am task2

      - name : task3
        debug : 
          msg : hey i am task3


#ansible-playbook start_on_specific_task.yml --start-at-task "task2"  (this will start play from task2 and skip the task1)     
